[package]
edition = "2021"
name    = "newnum_proc_macros"
version = "0.0.9"

[lib]

proc-macro = true

[dependencies]
derive-syn-parse = "0.2.0"
proc-macro2      = "1.0.93"
quote            = "1.0.38"
syn              = { version = "2.0.96", features = [ "full" ] }
